### ISSUE TITLE
Run at startup, make it periodic

### ISSUE THREAD

**Issue by karthikb351** [aarthykc/ApprovalNotifier#1]
Run it in the background at start up. Maybe make a `.bat` file to execute the script with `pythonw.exe` and add it to a startup folder.

A simple way to make it periodic, without using any external libraries is use the threading/timer module in python.

This, for example, runs the `foo()` function every 1 second.

``` python
from datetime import datetime
from threading import Timer

class PeriodicTask(object):
    def __init__(self, interval, callback, daemon=True, **kwargs):
        self.interval = interval
        self.callback = callback
        self.daemon   = daemon
        self.kwargs   = kwargs

    def run(self):
        self.callback(**self.kwargs)
        t = Timer(self.interval, self.run)
        t.daemon = self.daemon
        t.start()

def foo():
    print datetime.now()

task = PeriodicTask(interval=1, callback=foo)
task.run()
```

**Comment by aarthykc** [comment]
from BeautifulSoup import BeautifulSoup
import mechanize
from StringIO import StringIO
from PIL import Image
from CaptchaParser import CaptchaParser
import cookielib
class PeriodicTask(object):
    def **init**(self, interval, callback, daemon=True, **kwargs):
        self.interval = interval
        self.callback = callback
        self.daemon   = daemon
        self.kwargs   = kwargs

```
    def run(self):
        self.callback(**self.kwargs)
        t = Timer(self.interval, self.run)
        t.daemon = self.daemon
        t.start()

        def foo():
            br = mechanize.Browser()
            br.set_handle_redirect(True)
            br.set_handle_referer(True)
            cj = cookielib.CookieJar()
            br.set_cookiejar(cj)
            response = br.open('
```

https://academics.vit.ac.in/student/stud_login.asp')
                html = response.read()
                soup = BeautifulSoup(html)
                im = soup.find('img', id='imgCaptcha')
                image_response = br.open_novisit(im['src'])
                img = Image.open(StringIO(image_response.read()))
                parser = CaptchaParser()
                captcha = parser.getCaptcha(img)

```
            br.select_form('stud_login')
            br.form['regno'] = '11BCE0350'
            br.form['passwd'] = 'ilovemypeace'
            br.form['vrfcd'] = str(captcha)

            br.submit()

            if(br.geturl() == "
```

https://academics.vit.ac.in/student/home.asp"):
                    print "-"_30
                    print " "_12+"SUCCESS"
                    print "-"*30
                    br.open('
https://academics.vit.ac.in/student/stud_home.asp')
                    response1 = br.open('
https://academics.vit.ac.in/student/student_outing_request.asp')
                    html1 = response1.read()
                    soup1 = BeautifulSoup(html1)
                    trs = soup1.findAll('tr')
                    index = 0
                    for tr in trs:
                        if(tr.text=="Sl.NoApply onApply ToLeave
TypeFromToNo. of Hrs"):
                            break
                            index = index + 1

```
                        outing_history = []
                        for tr in trs[index+1:]:
                            tds = tr.findAll('td')
                            outing_history.append({
                                'sl_no': tds[0].text,
                                'apply_on': tds[1].text,
                                'apply_to': tds[2].text,
                                'leave_type': tds[3].text,
                                'from': tds[4].text,
                                'to': tds[5].text,
                                'no_of_hrs': tds[6].text,
                                'approved_by': tds[7].text,
                                'approved_on': tds[8].text,
                                'approval_status': tds[9].text
                                })

                            print outing_history

                        else:
                            print"FAIL"

                            task = PeriodicTask(interval=1*60*60,
```

callback=foo)
                                task.run()

**Comment by sreeram-dev** [comment]
@karthikb351  Change `t` to `self.t` for time interval
I have seen sqlite threading issues (if she ever wants to use) and invalid bus states.
Presently it is just solving a invisible problem. But if you ever encounter it use this and try.
Reference: https://github.com/batra-mlp-lab/pcloudcv/pull/21/files Same issue with redis server.

@aarthykc  use markdown editor. Code is easier to read.

**Comment by aneesh-neelam** [comment]
@karthikb351: I just converted @aarthykc to Ubuntu, don't suggest her this Windows Batch file thing :-P 

@aarthykc: Seriously though, make it a generic Python application. Then it can be added to Cron in Linux/OS X or Task Scheduler in Windows. 

Or implement the periodic thing in Python, and add it to startup. That'll be the easiest.

**Comment by aneesh-neelam** [comment]
@karthikb351: Why do you suggest it to be made periodic?

**Comment by karthikb351** [comment]
@aneesh-neelam Periodic in the sense, it keeps polling every 5/10/15 minutes or whatever, looking for changes in the status.

**Comment by karthikb351** [comment]
How far we've all come. <3

**Comment by aarthykc** [comment]
thanks for the helpful comments @karthikb351 !

**Comment by sreeram-dev** [comment]
Yeah. This kind of projects brought back a lot of college memories. Great working with you all. @karthikb351 @aneesh-neelam @aarthykc
